<?xml version= "1.0"?>

<?xml-stylesheet type="text/css" href="donation_style.css"?>

<!--URL= https://jeffe150.github.io/XML-Project-3/Donation_Form.xml-->

<!DOCTYPE Donation_Form [
<!ELEMENT main (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT recur (#PCDATA)>
<!ATTLIST recur type (Yes | No) #REQUIRED>
<!ELEMENT donate (amount, designation, other, heading) >
<!ELEMENT amount (#PCDATA)>
<!ATTLIST amount type (500.00 | 250.00 | 100.00 | Other) #REQUIRED>
<!ELEMENT designation (#PCDATA)>
<!ATTLIST designation type (GreatestNeedFund | LifeLongLearning | Other) #REQUIRED>
<!ELEMENT Other (#PCDATA)>
<!ELEMENT card (heading, card_name, card_number, CVV, exp_month, exp_year) >
<!ELEMENT card_name (#PCDATA)>
<!ELEMENT card_number (#PCDATA)>
<!ELEMENT CVV (#PCDATA)>
<!ELEMENT exp_month (#PCDATA)>
<!ELEMENT exp_year (#PCDATA)>
<!ELEMENT billing (email, name, address)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT name (first, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT address (street, unit, city, state, zip, phone) >
<!ELEMENT street (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (CellPhone | HomePhone) #REQUIRED>
<!ELEMENT details (dedication, heading, notify, informed)>
<!ELEMENT dedication (#PCDATA)>
<!ATTLIST dedication type (None | InHonorOf | InMemoryOf) #REQUIRED>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT notify (#PCDATA)>
<!ELEMENT informed (#PCDATA)>
<!ATTLIST informed type (Yes | No) #REQUIRED>

]>

<Donation_Form>
  <main> Ebenezer Online Giving Form </main>
  <title> Make a Gift </title>
  <subtitle> Your safe and secure online donation directly advances Ebenezer's
     mission. We are driven to heal, discover and educate for longer, healthier
     lives. With our partners at Fairview Health Services and MHealth, Ebenezer
      provides access throughout Minnesota to a full range of senior housing options,
      community-based programs and medical care. </subtitle>

    <donate>
      <heading> Donation Amount </heading>
      <amount type="500.00"> $500.00 </amount>
      <designation type="Other">Horticultural Therapy Program </designation>
      <recur type="Yes"> Make this donation recurring: </recur>
    </donate>

    <card>
      <heading> Payment </heading>
      <card_name> Jane Doe </card_name>
      <card_number> 1234-5678-9101-1121 </card_number>
      <CVV> 123 </CVV>
      <exp_month> 01 </exp_month>
      <exp_year> 2020 </exp_year>
    </card>

    <billing>
      <heading> Billing </heading>
      <email> janedoe@gmail.com </email>
      <name>
        <first> Jane </first>
        <last> Doe </last>
      </name>
      <address>
        <street> 123 Imaginary Street </street>
        <unit> Apt. 101</unit>
        <city> Minneapolis </city>
        <state> MN </state>
        <zip> 55401 </zip>
      </address>
      <phone type="Cell Phone"> 123-456-7890 </phone>
      <phone type="Home Phone"> 098-765-4321 </phone>
    </billing>

    <details>
      <heading> Dedications and Notifications </heading>
      <dedication type="In Honor Of"> Paula Vollmar-Heywood </dedication>
      <notify> Paula Vollmar-Heywood </notify>
      <informed type="Yes"> </informed>
    </details>

</Donation_Form>
